apiVersion: v1
kind: Service
metadata:
  name: {{ include "apisix.fullname" . }}
  labels:
    {{- include "apisix.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 9080
      protocol: TCP
      name: http
    - port: {{ .Values.service.tlsPort }}
      targetPort: 9443
      protocol: TCP
      name: https
  selector:
    {{- include "apisix.selectorLabels" . | nindent 4 }}
