apiVersion: v1
name: nacos
keywords:
  - kafka
  - cmak
description: A Nacos Helm chart for Kubernetes
home: https://github.com/scott-wong/nacos-chart
maintainers:
- name: scott-wong

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application
version: 0.1.0
appVersion: "1.2"

