{{- if ne .Values.global.mode "quickstart" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: nacos-cm
data:
  {{- with .Values.mysql }}
  mysql.db.name: {{ .database }}
  mysql.port: "{{ .databasePort }}"
  mysql.user: {{ .user }}
  mysql.password: {{ .password }}
  {{- end }}
{{- end }}
